name: Deploy

on:
  push:
    branches: [ "fix" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag video-restream

      - name: Save Docker image to tar file
        run: docker save -o video-restream.tar video-restream

      - name: Copy Docker image to remote server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" video-restream.tar ${{ secrets.USER }}@${{ secrets.SERVER }}:/home/${{ secrets.USER }}/tars

      - name: Deploy Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER }}
            docker load -i /home/${{ secrets.USER }}/tars/video-restream.tar
            docker stop video-restream || true
            docker rm video-restream || true
            docker run -d --name video-restream -p 9091:9091 video-restream
